### ISSUE TITLE
I cannot use network:

### ISSUE THREAD

**Issue by Koolkatze** [meowstercatel/r1-apk-patcher#3]
I can't use cellular network connection, that makes it tell me couldn't connect to the OS

**Comment by Koolkatze** [comment]
> I can't use cellular network connection, that makes it tell me couldn't connect to the OS

Solved by renaming SIM1 to SIM

**Comment by Koolkatze** [comment]
Still unable to connect to rabbit OS

**Comment by meowstercatel** [comment]
TLDR: the app won't work.

To get the app to a working state, some reverse engineering would be needed to be done.
Also, the "can't connect to rabbit os" error is related to the authentication keys being invalid (app version, os version) and I just don't want to update them for no reason.
